name: Update GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Corre automáticamente todos los días a medianoche
  workflow_dispatch: # Te permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula
        env:
          # Pasamos los modificadores visuales como variables de entorno
          # Así la acción los lee internamente sin chocar con la validación estricta de inputs
          NO_FRAME: true
          NO_BG: true

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p src
          git add src/
          git commit -m "Update profile trophies with private data" || exit 0
          git push
