name: Update GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to manually click "Run" to test it

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # You can add your preferred theme/arguments here:
          params: '&theme=dracula&no-frame=true&no-bg=true&margin-w=4'

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/
          git commit -m "Update profile trophies with private data" || exit 0
          git push
